### ISSUE TITLE
Beta channel

### ISSUE THREAD

**Issue by rjanvier** [flathub/org.cloudcompare.CloudCompare#37]
Hi Guys. I'm in the process of updating the flatpak for 2.13 (beta comming next WE)
- Is it possible to create a beta branch (and thus a beta "channel") for this repository?
- At the inception of the repo, you sent me an invitation to collaborate to it (with commit rights I guess) but I remember that when I tried to join it has expired. Is it possible to resend me a invitation? 
Thanks a lot.

**Comment by christian-rauch** [comment]
> Is it possible to create a beta branch (and thus a beta "channel") for this repository?

I can create a branch called `beta` but I don't know how to make Flathub use the beta branch.


> Is it possible to resend me a invitation?

@nedrichards created the repo originally and invited the initial contributors. I don't see an option for me to do the same.


@nedrichards @bilelmoussaoui Can you invite @rjanvier to this repo and let us know how we can create a beta channel for Flathub?

**Comment by rjanvier** [comment]
Thank you Christian!

**Comment by bilelmoussaoui** [comment]
Sorry for the long delay. I invited @rjanvier to the repository. For the beta channel, just push to the beta branch that should be all you need.

**Comment by christian-rauch** [comment]
@rjanvier Is this issue resolved for you? Do you have access to the repo now?

**Comment by christian-rauch** [comment]
When I use CloudCompare, I am using the stable version from this Flatpak. I haven't built the master branch for a long time.

If the current version on master builds, it would be worth pushing this to a `beta` branch so this can be tested using the Flatpak runtime instead of the system libraries. The issue was reported against Ubuntu 18.04 which is EOL now.

**Comment by rjanvier** [comment]
I'm affected too in 22.04 and I think [this](https://github.com/CloudCompare/CloudCompare/issues/1873) is related. It reports the issue exists also in the flatpak. I will try to propose a PR for the beta channel in the coming week

**Comment by rjanvier** [comment]
closed by #66
