### ISSUE TITLE
Missing dependencies LASzip or LAZperf 

### ISSUE THREAD

**Issue by DennaGherlyn** [flathub/org.cloudcompare.CloudCompare#4]
CloudCompare flatpak version: 2.11

When trying to open compressed `.laz` files I'm getting the following error:
```
PDAL exception: readers.las: Can't read compressed file without LASzip or LAZperf decompression library.
```
Would it be possible to include either of these libraries in the flatpak?

**Comment by dgirardeau** [comment]
I don't know exactly how this works, but I believe you need to compile PDAL with LAZ support (via LASzip or LAZperf). Therefore it seems the flatpak version doesn't rely on the right version of PDAL?

**Comment by chippey** [comment]
I just got hit with this as well.  Building with LASzip or LAZperf would help a lot!

**Comment by christian-rauch** [comment]
The flatpak is using PDAL 1.9.1 without any special flags:
https://github.com/flathub/org.cloudcompare.CloudCompare/blob/d2ac52a71eb0a6774267c9a5bafb9d1b2c1d21b3/org.cloudcompare.CloudCompare.yaml#L123-L131

Is upgrading the version sufficient? One of you can send a PR with a newer version or the correct build flags. The CI will then build a version with that flatpak specification and you can test if it solves your problem. If the new specification solves your issue, I am going to merge it.

**Comment by chippey** [comment]
Just downloaded Peek to make a screen recording, but it seems it doesn't record the full window so the top got cut off - apologies for that.
![Peek 2022-08-10 17-05](https://user-images.githubusercontent.com/3241883/184028995-c54c413d-ba50-405b-8823-7c616579ffea.gif)
