### ISSUE TITLE
include/pdal directory has too restrictive permissions

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.cloudcompare.CloudCompare#57]
See https://github.com/PDAL/PDAL/issues/4258

This causes the runners in flathub to fail and make unrelated builds fail as it can't delete that directory.

Please run something like `chmod -R u+w /app/include/pdal` as post-install to "fix" it.

**Comment by christian-rauch** [comment]
Can you send a PR?

Overall, I think this is an issue with the flathub build infrastructure. Builds should be isolated such that they don't interfere with each other. How do snapcraft or Debian packages handle this situation?

**Comment by bbhtt** [comment]
> Can you send a PR?

You aren't affected at the moment. Just make sure not to update to PDAL 2.6.0 or 2.6.1 without the upstream patch or that command and that no test builds reach installing PDAL too.

**Comment by christian-rauch** [comment]
Fixed in b4c04de3930421dc09c01854c1fb850d489f9094.

**Comment by bbhtt** [comment]
Thanks!
